import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../dist/engine.js';
const card=(s,r)=>({suit:s,rank:r,id:s+r});
const hand=spec=>Object.entries(spec).flatMap(([s,rs])=>rs.split(' ').filter(Boolean).map(r=>card(s,Number({A:14,K:13,Q:12,J:11,T:10}[r]||r))));
function auction(bids,dealer=0){const s=E.createDeal(dealer+1);bids.forEach(b=>E.makeCall(s,b));return s.auction;}
test('deal has 52 unique cards, 40 HCP, rotating dealer and vulnerability',()=>{const d=E.createDeal(4);assert.equal(new Set(d.hands.flat().map(c=>c.id)).size,52);assert.deepEqual(d.hands.map(h=>h.length),[13,13,13,13]);assert.equal(d.hands.reduce((n,h)=>n+E.hcp(h),0),40);assert.equal(d.dealer,3);assert.deepEqual(d.vulnerable,[true,true]);assert.deepEqual(E.vulnerability(17),[false,false]);});
test('legal auction, doubles, redoubles, declarer, and passed-out board',()=>{let a=auction(['1H']);assert(!E.legalCalls(a,1).includes('1D'));assert(E.legalCalls(a,1).includes('X'));a=auction(['1H','X']);assert(E.legalCalls(a,2).includes('XX'));a=auction(['1H','X','XX','P','2H','P','4H','P','P','P']);assert.equal(E.getContract(a).declarer,0);assert.equal(E.getContract(a).doubled,1);const s=E.createDeal();['P','P','P','P'].forEach(b=>E.makeCall(s,b));assert.equal(s.phase,'complete');assert.equal(s.result.passedOut,true);});
test('follow suit is mandatory, trump beats lead, off-suit ace cannot win',()=>{const h=[card('H',2),card('S',14)];const t=[{seat:0,card:card('H',13)}];assert.deepEqual(E.legalCards(h,t),[h[0]]);assert.equal(E.trickWinner([...t,{seat:1,card:card('S',14)}],'N'),0);assert.equal(E.trickWinner([...t,{seat:1,card:card('S',2)}],'S'),1);});
test('duplicate scoring covers games, slams, doubled/redoubled contracts and penalties',()=>{const cases=[['N',3,1,9,false,400],['N',3,1,10,true,630],['H',4,1,10,false,420],['C',5,1,11,true,600],['S',6,1,12,false,980],['N',7,1,13,true,2220],['S',2,2,8,false,470],['H',4,2,11,true,990],['N',1,4,7,false,560],['H',4,1,8,true,-200],['H',4,2,9,false,-100],['H',4,2,8,false,-300],['H',4,2,7,false,-500],['H',4,2,6,false,-800],['H',4,2,7,true,-800],['H',4,4,7,true,-1600]];for(const [suit,level,doubled,tricks,v,expected]of cases)assert.equal(E.scoreContract({suit,level,doubled},tricks,v).score,expected,JSON.stringify([suit,level,doubled,tricks,v]));});
test('2/1 applies only to nonjump, unpassed, uncontested responses',()=>{assert.equal(auction(['1S','P','2C'])[2].force,'game');assert.equal(auction(['1D','P','2C'])[2].force,'game');assert.equal(auction(['1C','P','2H'])[2].kind,'soloway');assert.notEqual(auction(['1C','P','2H'])[2].kind,'two-over-one');assert.notEqual(auction(['1S','2H','3C'])[2].force,'game');assert.notEqual(auction(['1S','X','2C'])[2].force,'game');assert.notEqual(auction(['P','P','1S','P','2C'])[4].force,'game');assert.equal(auction(['1S','P','1N'])[2].force,'round');assert.notEqual(auction(['1S','X','1N'])[2].force,'round');});
test('forcing NT produces an opener rebid even with a balanced minimum',()=>{const h=hand({S:'A K 8 5 2',H:'Q 7 4',D:'K 6 3',C:'9 2'});const a=auction(['1S','P','1N','P']);const b=E.chooseBid(h,a,0).bid;assert.notEqual(b,'P');assert(E.legalCalls(a,0).includes(b));});
test('bot chooses 2/1 with game values and reaches game after opener rebids',()=>{const h=hand({S:'7 2',H:'A Q 9 3',D:'K J 8 4',C:'K 6 2'});const a=auction(['1S','P']);assert.equal(E.chooseBid(h,a,2).bid,'2D');const b=auction(['1S','P','2D','P','2S','P']);const choice=E.chooseBid(h,b,2).bid;assert(E.isGame(choice));});
test('Stayman and transfers are recognized and answered',()=>{const h=hand({S:'K J 8',H:'A Q 9 3',D:'K 6 2',C:'K 7 4'});let a=auction(['1N','P','2C','P']);assert.equal(E.chooseBid(h,a,0).bid,'2H');a=auction(['1N','P','2D','P']);assert.equal(E.chooseBid(h,a,0).bid,'2H');});
test('500 deterministic bot boards terminate, preserve cards and follow suit',()=>{let seed=917;const rng=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};for(let i=1;i<=500;i++){const s=E.createDeal(i,rng);let calls=0;while(s.phase==='bidding'){assert(calls++<150);const b=E.botBid(s).bid;assert(E.legalCalls(s.auction,s.turn).includes(b));E.makeCall(s,b);}let cards=0;while(s.phase==='play'){if(s.trick.length===4){E.collectTrick(s);continue;}const c=E.botCard(s);assert(E.legalCards(s.hands[s.turn],s.trick).some(x=>x.id===c.id));E.playCard(s,c.id);cards++;}if(!s.result.passedOut){assert.equal(cards,52);assert.equal(s.tricks[0]+s.tricks[1],13);assert.equal(s.hands.flat().length,0);assert.equal(new Set(s.history.flatMap(t=>t.cards.map(x=>x.card.id))).size,52);}assert(Number.isFinite(s.result.score));}});
